# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # 添加资源包
#   pod 'TencentCloudHuiyanSDKFace_framework', :path => '../Framework/TencentCloudHuiyanSDKFace_framework'
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # 确保资源包被正确复制
    if target.name == 'Runner'
      target.build_phases.each do |build_phase|
        if build_phase.respond_to?(:name) && build_phase.name == "Copy Bundle Resources"
          # 添加资源包
#           build_phase.add_file_reference(installer.pods_project.new_file("../Framework/TencentCloudHuiyanSDKFace_framework/Resources/TencentCloudHuiyanSDKFace.bundle"))
#           build_phase.add_file_reference(installer.pods_project.new_file("../Framework/TencentCloudHuiyanSDKFace_framework/Resources/face-tracker-v003.bundle"))
        end
      end
    end
  end
end
